config/routes.rb
SakaiWidgetlibrary::Application.routes.draw do

  # Routes for devise authentication
  devise_for :users, :controllers => {:sessions => 'sessions'}, :skip => [:sessions] do
    get  '/' => "home#index", :as => :new_user_session
    post '/login' => 'sessions#create', :as => :user_session
    get  '/logout' => 'devise/sessions#destroy', :as => :logout
    get  '/register' => 'devise/registrations#new', :as => :user_registration
    post '/register' => 'registrations#create', :as => :user_registration
    get  '/register' => 'devise/registrations#new', :as => :new_user_registration
    get  '/register/check_username/:username' => 'registrations#check_username'
    get  '/forgot_password' => 'devise/passwords#new', :as => :new_user_password
    post '/forgot_password' => 'passwords#create', :as => :user_password
    put  '/forgot_password' => 'passwords#update', :as => :user_password
    put  '/register' => 'registrations#update', :as => :edit_user_registration
    get  '/edit' => 'devise/registrations#edit', :as => :edit_user_registration
  end

  # Application-level routes
  match '/search' => 'application#search'

  # Browse
  match '/browse(/:category_title)' => 'browse#index', :as => :browse

  # Widget Details
  get   '/widget/:title' => 'widget#show', :as => :widget
  post  '/widget/:title/rate' => 'widget#rating_create', :as => :ratings
  put   '/widget/:title/rate' => 'widget#rating_update', :as => :ratings

  # Widget code (hijacking paperclip's route)
  get   '/widget/:title/:version/download' => "widget#download", :as => :widget_download
  get   '/widget/:title/:version/backend/download' => "widget#download_backend", :as => :widget_download_backend

  # Widget Submission (Versions)
  resources :versions, :path => "submit", :controller => "submit"

  # Users
  get '/user/:id-:url_title' => 'user#index', :as => :user

  # My Widgets
  match '/mywidgets' => 'mywidgets#index', :as => :mywidgets
  match '/mywidgets/submissions' => 'mywidgets#submissions', :as => :mywidgets_submissions

  # SDK
  match '/sdk' => 'sdk#index', :as => :sdk
  match '/sdk/*section' => 'sdk#sdk_section'
  match '/zippedwidget' => 'widget_generator#zippedwidget'


  # Admin section
  match '/admin/users' => 'admin#users', :as => :admin_users
  match '/admin/users/admin' => 'admin#adminusers', :as => :admin_admin_users
  match '/admin/users/delete/:id' => 'admin#delete_user', :as => :admin_delete_user
  match '/admin/options' => 'admin#options', :as => :admin_options
  match '/admin/languages/edit/:id' => 'admin#edit_language', :as => :admin_edit_language
  post  '/admin/languages/save' => 'admin#save_language', :as => :admin_add_edit_language
  delete  '/admin/languages/remove/:id' => 'admin#remove_language', :as => :admin_remove_language
  match '/admin/categories' => 'admin#categories', :as => :admin_categories
  match '/admin/categories/edit/:id' => 'admin#edit_category', :as => :admin_edit_category
  post  '/admin/categories/save' => 'admin#save_category', :as => :admin_add_edit_category
  delete '/admin/categories/remove/:id' => 'admin#remove_category', :as => :admin_remove_category
  match '/admin/statistics' => 'admin#statistics', :as => :admin_statistics
  match '/admin' => 'admin#widgets'
  match '/admin/widgets(/:state)' => 'admin#widgets', :as => :admin
  match '/admin/widgets/:review/:version_id' => 'admin#reviewed', :as => :admin_review_widget
  post  '/admin/users/update' => 'admin#user_update', :as => :update

  # Errors
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#e404'
  end
  get "errors/e404"
  get "errors/e500"

  root :to => 'home#index'

end

app/views/admin/_add_edit_items.html.erb
<%= form_for(@item, :url => @config[:urls][:save], :method => "POST", :html => { :class => "wl-form-field-wrapper", :id => "admin_item_add_edit_form" }) do |f| %>
    <% if @item.errors.any? %>
        <ul class="admin-error-box">
            <% @item.errors.full_messages.each do |message| %>
                <li><span class="wl-error"><%= message %></li>
            <% end %>
        </ul>
    <% end %>
    <input type="hidden" name="add_new" value="<%= add_new %>" />
    <input type="hidden" name="id" value="<%= id  %>" />
    <% @config[:db_properties].zip(@config[:table_headings]) do |property, display_name| %>
        <div class="wl-field">
            <%= f.label property %>
            <%= f.text_field property %>
        </div>
    <% end %>
    <div class="admin-submit-buttons">
        <% if add_new != true %>
            <%= link_to 'Cancel', @config[:urls][:base], :class => "wl-regular-link" %>
        <% end %>
        <% submit_msg = (add_new == true) ? "Add Entry" : "Save Changes" %>
        <%= f.submit submit_msg, :class => "wl-button wl-overlay-button" %>
    </div>
<% end %>

app/views/admin/_admin_table.html.erb
<table class="admin-table">
    <thead>
        <% @config[:table_headings].each do |heading| %>
            <th><%= heading %></th>
        <% end %>
        <th>Actions</th>
    </thead>
    <tbody>
        <% @results.each do |result| %>
            <tr>
                <% @config[:db_properties].each do |property| %>
                    <td><%= result[property] %></td>
                <% end %>
                <td class="admin-table-actions">
                    <%= link_to "Edit", "#{@config[:urls][:edit]}#{result.id}", :class => "wl-button wl-overlay-button" %>
                    <%= form_tag @config[:urls][:remove], :method => "POST", :class => "admin_item_remove_form" do %>
                        <input type="hidden" name="id" value="<%= result.id %>" />
                        <% confirm_message = @items_used.include?(result.id) ?
                            "This item is being used by widgets.\nAre you sure you want to remove this entry?" :
                            "Are you sure you want to remove this entry?"
                        %>
                        <%= link_to 'Remove', [@config[:urls][:remove], result.id].join, :confirm => confirm_message, :method => :delete, :class => "wl-button wl-overlay-button" %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/_lhnav.html.erb
<nav id="lhnavigation_container">
  <% if params[:action].eql?"widgets" %>
  <h1 class="wl-bold">All Widgets</h1>
  <ul>
      <li<% if !params[:state] %> class="selected wl-bold"<% end %>>
        <div><%= link_to "Widgets to review", admin_path %></div>
      </li>
      <li<% if params[:state] %> class="selected wl-bold"<% end %>>
        <div><%= link_to "Declined widgets", admin_path(:state => State.declined) %></div>
      </li>
  </ul>
  <% elsif ["users", "adminusers"].include?(params[:action]) %>
  <h1 class="wl-bold">User Management</h1>
  <ul>
    <li class="navigation_item <% if params[:action].eql?("users") %> selected<% end %>"><div><%= link_to "All Users", admin_users_path %></div></li>
    <li class="navigation_item <% if params[:action].eql?("adminusers") %> selected<% end %>"><div><%= link_to "Admin Users", admin_admin_users_path %></div></li>
  </ul>
  <% elsif ["options", "languages", "edit_language", "categories", "edit_category", "save_language", "save_category"].include?(params[:action]) %>
  <h1 class="wl-bold">Widget Options</h1>
  <ul>
    <li class="navigation_item <% if ["options", "edit_language", "save_language"].include?(params[:action]) %> selected<% end %>"><div><%= link_to "Languages", admin_options_path %></div></li>
    <li class="navigation_item <% if ["categories", "edit_category", "save_category"].include?(params[:action]) %> selected<% end %>"><div><%= link_to "Categories", admin_categories_path %></div></li>
  </ul>
  <% elsif params[:action].eql?"statistics" %>
  <h1 class="wl-bold">Statistics</h1>
  <ul>
    <li <% if params[:action].eql?("statistics")%>class="selected" <% end %>>
      <div><%= link_to "Users and widgets", admin_statistics_path %></div>
    </li>
  </ul>
  <% end %>
</nav>
<hr class="wl-push wl-hidden"/>

app/views/admin/_nav.html.erb
<nav id="widgetlibrary_navigation">
    <ul class="wl-bold">
        <li class="navigation_item<% if params[:action].eql?("widgets") %> selected<% end %>"><%= link_to "Widget Review", admin_path %></li>
        <% if is_admin? %>
            <li class="navigation_item<% if ["users", "adminusers"].include?(params[:action]) %> selected<% end %>"><%= link_to "Users", admin_users_path %></li>
            <li class="navigation_item<% if ["options", "edit_language", "categories", "edit_category", "save_category", "save_language"].include?(params[:action]) %> selected<% end %>"><%= link_to "Widget Options", admin_options_path %></li>
            <li class="navigation_item<% if params[:action].eql?("statistics")%> selected<% end %>"><%= link_to "Statistics", admin_statistics_path %></li>
        <% end %>
    </ul>
</nav>

app/views/admin/_user.html.erb
<% @users.each_with_index do |user, index| %>
    <% if index % 3 == 0 %>
        <div class="wl-push">
    <% end %>
    <li class="wl-left">
        <%= form_for user, :url => "/admin/users/update", :method => "POST", :remote => true do |f| %>
            <%= image_tag user.avatar.url(:thumb), :alt => "#{user.name}'s Photo", :class => "wl-left"%>
            <%= link_to user.name, user_path(:id => user.id, :url_title => user.url_title), :class => "wl-bold wl-regular-link", :target => "_blank" %>
            -
            <%= link_to "Delete", admin_delete_user_path(user), :confirm => "Are you sure you want to delete this user?", :class => "wl-bold wl-regular-link", :method => "delete" %>
            <span class="wl-no-script">-</span>
            <%= button_tag "Save", :class => "wl-no-script wl-button wl-link-button wl-regular-link wl-save-fallback" %>
            <br/>
            <input type="hidden" name="user_id" value="<%= user.id %>">
            <label class="label" for="chk_user_admin<%= user.id %>">Administrator:</label>
            <% if user_signed_in? && current_user.id != user.id %>
                <%= check_box_tag "chk_user_admin#{user.id}", 1, user.admin %>
            <% else %>
                <%= check_box_tag "chk_user_admin#{user.id}", 1, user.admin, :disabled => true %>
            <% end %>
            <label class="label" for="chk_user_reviewer<%= user.id %>">Reviewer:</label>
            <% if user_signed_in? && current_user.id != user.id %>
                <%= check_box_tag "chk_user_reviewer#{user.id}", 1, user.reviewer %>
            <% else %>
                <%= check_box_tag "chk_user_reviewer#{user.id}", 1, user.reviewer, :disabled => true %>
            <% end %>
        <% end %>
    </li>
    <% if (index + 1) % 3 == 0 %>
        </div>
    <% end %>
<% end %>

app/views/admin/_widget.html.erb
<% version = Version.where("widget_id = ? AND state_id = ?", widget.id, params[:state] || State.pending).order("created_at desc").limit(1).first %>
<tr>
  <td><%= link_to version.title, widget_path(:title => widget.url_title), :class => "wl-regular-link wl-bold wl-widget-item_widgetname" %></td>
  <td><%= widget.user.name %></td>
  <td><%= version.created_at.localtime.strftime("%B %e, %Y %l:%M%P") %></td>
  <td><%= version.version_number %></td>
  <% if params[:state].to_s.eql? State.declined.to_s %>
  <td><%= version.reviewer.name %></td>
  <td><%= auto_link(version.notes, :html => {:class => 'wl-regular-link'}) %></td>
  <% end %>
</tr>

app/views/admin/adminusers.html.erb
<h1>Admin Users</h1>
<ul class="admin_userlist">
    <%= render :partial => "user", :users => @users %>
</ul>

app/views/admin/categories.html.erb
<h2>Available Categories</h2>
<%= render :partial => 'admin_table', :results => @results, :items_used => @items_used, :config => @config %>
<hr class="wl-split-line" />
<h2>Add New Category</h2>
    <%= render :partial => "add_edit_items", :config => @config, :locals => { :add_new => true, :id => nil, :existing_entry => nil } %>
<hr class="wl-push wl-hidden" />

app/views/admin/edit_category.html.erb
<h2>Edit Category</h2>
<%= render :partial => "add_edit_items", :config => @config, :locals => { :add_new => false, :id => params[:id], :existing_entry => @category } %>

app/views/admin/edit_language.html.erb
<h2>Edit Language</h2>
<%= render :partial => "add_edit_items", :config => @config, :locals => { :add_new => false, :id => params[:id], :existing_entry => @language } %>

app/views/admin/languages.html.erb
<h2>Available Languages</h2>
<table class="admin-table">
    <thead>
        <th>Language</th>
        <th>Code</th>
        <th>Region</th>
        <th>Actions</th>
    </thead>
    <tbody>
        <% @languages.each do |language| %>
            <tr>
                <td><%= language.title %></td>
                <td><%= language.code %></td>
                <td><%= language.region %></td>
                <td class="admin-language-actions">
                    <a class="wl-button wl-overlay-button" href="/admin/languages/edit/<%= language.id %>">Edit</a>
                    <%= form_tag "/admin/languages/remove", :method => "POST", :class => "language_remove_form" do %>
                        <input type="hidden" name="id" value="<%= language.id %>" />
                        <button class="wl-button wl-overlay-button" title="Remove <%= language.title %>" type="submit">Remove</button>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<hr />
<h2>Add New Language</h2>
<%= render :partial => "edit_add_language", :locals => { :add_new => true, :id => nil, :language => nil } %>

app/views/admin/options.html.erb
<h2>Available Languages</h2>
    <%= render :partial => 'admin_table', :results => @results, :item => @item, :items_used => @items_used, :config => @config %>
<hr class="wl-split-line" />
<h2>Add New Language</h2>
    <%= render :partial => "add_edit_items", :config => @config, :locals => { :add_new => true, :id => nil, :existing_entry => nil } %>
<hr class="wl-push wl-hidden" />

app/views/admin/statistics.html.erb
<h2>User and widget statistics</h2>
<h3>Number of registered users</h3>
<%= @user_count %> users registered in the system

<h3>Users with most logins</h3>
<ol>
  <% @users_login_ranking.each do |user| %>
    <li><%= link_to user.name, user_path(:id => user.id, :url_title => user.url_title), :class => "wl-regular-link" %> logged in <%= user.sign_in_count %> times</li>
  <% end %>
</ol>

<h3>Users with most widgets</h3>
<ol>
  <% @users_widget_ranking.each do |user| %>
    <li><%= link_to user.name, user_path(:id => user.id, :url_title => user.url_title), :class => "wl-regular-link" %> submitted <%= user.total %> widgets</li>
  <% end %>
</ol>

<h3>Number of submitted widgets</h3>
<%= @widget_count %> widgets in the system

<h3>Average rating per widget</h3>
Average rating of <%= @rating_average %> per widget

<h3>Number of reviews</h3>
<%= @rating_count %> reviews submitted

app/views/admin/users.html.erb
<h1>All users</h1>
<ul class="admin_userlist">
    <%= render :partial => "user", :users => @users %>
</ul>