config/routes.rb
SakaiWidgetlibrary::Application.routes.draw do

  # Routes for devise authentication
  devise_for :users, :controllers => {:sessions => 'sessions'}, :skip => [:sessions] do
    get  '/' => "home#index", :as => :new_user_session
    post '/login' => 'sessions#create', :as => :user_session
    get  '/logout' => 'devise/sessions#destroy', :as => :logout
    get  '/register' => 'devise/registrations#new', :as => :user_registration
    post '/register' => 'registrations#create', :as => :user_registration
    get  '/register' => 'devise/registrations#new', :as => :new_user_registration
    get  '/register/check_username/:username' => 'registrations#check_username'
    get  '/forgot_password' => 'devise/passwords#new', :as => :new_user_password
    post '/forgot_password' => 'passwords#create', :as => :user_password
    put  '/forgot_password' => 'passwords#update', :as => :user_password
    put  '/register' => 'registrations#update', :as => :edit_user_registration
    get  '/edit' => 'devise/registrations#edit', :as => :edit_user_registration
  end

  # Application-level routes
  match '/search' => 'application#search'

  # Browse
  match '/browse(/:category_title)' => 'browse#index', :as => :browse

  # Widget Details
  get   '/widget/:title' => 'widget#show', :as => :widget
  post  '/widget/:title/rate' => 'widget#rating_create', :as => :ratings
  put   '/widget/:title/rate' => 'widget#rating_update', :as => :ratings

  # Widget code (hijacking paperclip's route)
  get   '/widget/:title/:version/download' => "widget#download", :as => :widget_download
  get   '/widget/:title/:version/backend/download' => "widget#download_backend", :as => :widget_download_backend

  # Widget Submission (Versions)
  resources :versions, :path => "submit", :controller => "submit"

  # Users
  get '/user/:id-:url_title' => 'user#index', :as => :user

  # My Widgets
  match '/mywidgets' => 'mywidgets#index', :as => :mywidgets
  match '/mywidgets/submissions' => 'mywidgets#submissions', :as => :mywidgets_submissions

  # SDK
  match '/sdk' => 'sdk#index', :as => :sdk
  match '/sdk/*section' => 'sdk#sdk_section'
  match '/zippedwidget' => 'widget_generator#zippedwidget'


  # Admin section
  match '/admin/users' => 'admin#users', :as => :admin_users
  match '/admin/users/admin' => 'admin#adminusers', :as => :admin_admin_users
  match '/admin/users/delete/:id' => 'admin#delete_user', :as => :admin_delete_user
  match '/admin/options' => 'admin#options', :as => :admin_options
  match '/admin/languages/edit/:id' => 'admin#edit_language', :as => :admin_edit_language
  post  '/admin/languages/save' => 'admin#save_language', :as => :admin_add_edit_language
  delete  '/admin/languages/remove/:id' => 'admin#remove_language', :as => :admin_remove_language
  match '/admin/categories' => 'admin#categories', :as => :admin_categories
  match '/admin/categories/edit/:id' => 'admin#edit_category', :as => :admin_edit_category
  post  '/admin/categories/save' => 'admin#save_category', :as => :admin_add_edit_category
  delete '/admin/categories/remove/:id' => 'admin#remove_category', :as => :admin_remove_category
  match '/admin/statistics' => 'admin#statistics', :as => :admin_statistics
  match '/admin' => 'admin#widgets'
  match '/admin/widgets(/:state)' => 'admin#widgets', :as => :admin
  match '/admin/widgets/:review/:version_id' => 'admin#reviewed', :as => :admin_review_widget
  post  '/admin/users/update' => 'admin#user_update', :as => :update

  # Errors
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#e404'
  end
  get "errors/e404"
  get "errors/e500"

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    args = {
      :active => true
    }
    @recentlyadded = Widget.where(args).includes(:versions).order("versions.released_on desc").limit(5)
    @toprated = Widget.where(args).order("average_rating desc").limit(16)
    @mostpopular = Widget.where(:active => true).order("num_downloads desc, num_ratings desc, average_rating desc").limit(5)
  end
end

app/views/home/_mostpopular.html.erb
<div id="widgetlibrary_mostpopular" class="wl-inset-shadow-container wl-content-145">
    <h1>Most Popular</h1>
    <%= render :partial => "core/widget", :locals => {:display => {:rating => true, :ellipsis => 1, :icon_size => "smaller"}}, :collection => @mostpopular %>
    <hr class="wl-push wl-hidden">
</div>

app/views/home/_recentlyadded.html.erb
<div id="widgetlibrary_recentlyadded" class="wl-inset-shadow-container wl-content-145">
    <h1>Recently Added</h1>
    <%= render :partial => "core/widget", :locals => {:display => {:added => true, :icon_size => "smaller", :ellipsis => 1}}, :collection => @recentlyadded %>
    <hr class="wl-push wl-hidden">
</div>

app/views/home/_toprated.html.erb
<div id="widgetlibrary_toprated" class="wl-inset-shadow-container wl-content-710">
    <h1>Top Rated</h1>
    <%= render :partial => "core/widget", :locals => {:display => {:rating => true, :author => true, :num_ratings => true}}, :collection => @toprated %>
    <hr class="wl-push wl-hidden"/>
    <div id="home_footer">
      <%= link_to "Browse all widgets", browse_path, :id => "show_more", :class => "wl-button wl-large-button" %>
    </div>
</div>

app/views/home/index.html.erb
<div class="wl-content-container" id="index_container">
    <div class="wl-content-165 wl-right">
        <%= render :partial => "recentlyadded" %>
        <%= render :partial => "mostpopular"%>
        <%= render :partial => "pagewidgets/submitwidget" %>
    </div>

    <div class="wl-content-730 wl-left">
        <div id="widgetlibrary_carousel">
            <div id="widgetlibrary_homecarousel" style="visibility:hidden;">
                <div class="slides_container">
                    <div id="carousel_state1" class="widgetlibrary_homecarousel_pane">
                        <h1>Over <strong>200</strong> ways to customize and enhance collaborative academic learning experiences</h1>
                        <h2>A 'Widget' is an app which can be used as a 'bolt on' to the installed Sakai Open Academic Environment to add additional functionality, expanding the value of the platform for tutors and students alike.</h2>
                    </div>
                    <div id="carousel_state2" class="widgetlibrary_homecarousel_pane">
                        <h1>By adding custom widgets to Apereo OAE, you’ll be enriching the learning experience for students and staff alike.</h1>
                        <h2>A handful of the Universities benefiting from Apereo OAE:</h2>
                    </div>
                    <div id="carousel_state3" class="widgetlibrary_homecarousel_pane">
                        <h1 class="size-30">Design. Code. Submit.</h1>
                        <h1>Submitting your new widget couldn’t be simpler</h1>
                        <h2>Once you’ve uploaded your widget, we will evaluate its suitability and code, and get back to you within a few days with a 'yes' or some suggested improvements. <%= link_to "Submit new widget", new_version_path, :class => "wl-link-button wl-button wl-overlay-button"%></h2>
                    </div>
                </div>
                <ul class="carousel_pagination">
                    <li class="carousel_choice" class="current">
                        <div class="carousel_choice_arrow" id="carousel_choice_arrow_1" style="display:none;"></div>
                        <%= link_to "What is a Widget?", "#0", :class => "widgetlibrary_homecarousel_navitem", "data-carousel-index" => "1" %>
                    </li>
                    <li class="carousel_choice">
                        <div class="carousel_choice_arrow" id="carousel_choice_arrow_2" style="display:none;"></div>
                        <%= link_to "Create the unexpected", "#1", :class => "widgetlibrary_homecarousel_navitem", "data-carousel-index" => "2" %>
                    </li>
                    <li class="carousel_choice">
                        <div class="carousel_choice_arrow" id="carousel_choice_arrow_3" style="display:none;"></div>
                        <%= link_to "Submit a widget", "#2", :class => "widgetlibrary_homecarousel_navitem", "data-carousel-index" => "3" %>
                    </li>
                </ul>
            </div>
        </div>

        <hr class="wl-push wl-hidden"/>

        <%= render :partial => "toprated" %>
    </div>
    <hr class="wl-push wl-hidden"/>
</div>

app/views/home/library.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "library" %>
<% end %>

<div class="wl-content-container" id="library_container">
    <div class="wl-content-710 wl-right wl-padding-15-0 wl-padding-0-10 " id="library_widgets">
        <%= render :partial => "pagewidgets/featured" %>
        <%= render :partial => "pagewidgets/allcategories" %>
    </div>
    <div class="wl-content-185 wl-left wl-padding-15-0">
        <%= render :partial => "pagewidgets/lhnavigation" %>
    </div>
    <hr class="wl-push wl-hidden"/>
</div>

app/views/home/widget.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "widget" %>
<% end %>

<div class="wl-content-container" id="widget_container">
    <div id="widget_download">
        <img src="../images/widget_small_preview.jpg" alt="<%= @widget %> preview">
        <a target="_blank" class="wl-button wl-header-button" href="#">Download</a>
    </div>
    <div id="widget_description">
        <h1 class="wl-bold">Activity Plus <span id="widget_version">v3.0</span></h1>
        by <a href="#" title="James Johnson" class="wl-regular-link">James Johnson</a>
        <p>A+ adds additional functionality to an already popular Sakai widget. Just few taps and your activity chart is ready. You can save it for later or email immediately.</p>
        <ul>
            <li>supports rotation,</li>
            <li>add new slices (up to 12),</li>
            <li>move slices on a chart in slice settings,</li>
            <li>change slice size,</li>
            <li>rotate whole chart, just swipe your finger next to chart border,</li>
            <li>skew and scale chart in real time,</li>
            <li>save for later, in chart settings, chart is saved with date and chart name.</li>
        </ul>
    </div>
</div>