config/routes.rb
SakaiWidgetlibrary::Application.routes.draw do

  # Routes for devise authentication
  devise_for :users, :controllers => {:sessions => 'sessions'}, :skip => [:sessions] do
    get  '/' => "home#index", :as => :new_user_session
    post '/login' => 'sessions#create', :as => :user_session
    get  '/logout' => 'devise/sessions#destroy', :as => :logout
    get  '/register' => 'devise/registrations#new', :as => :user_registration
    post '/register' => 'registrations#create', :as => :user_registration
    get  '/register' => 'devise/registrations#new', :as => :new_user_registration
    get  '/register/check_username/:username' => 'registrations#check_username'
    get  '/forgot_password' => 'devise/passwords#new', :as => :new_user_password
    post '/forgot_password' => 'passwords#create', :as => :user_password
    put  '/forgot_password' => 'passwords#update', :as => :user_password
    put  '/register' => 'registrations#update', :as => :edit_user_registration
    get  '/edit' => 'devise/registrations#edit', :as => :edit_user_registration
  end

  # Application-level routes
  match '/search' => 'application#search'

  # Browse
  match '/browse(/:category_title)' => 'browse#index', :as => :browse

  # Widget Details
  get   '/widget/:title' => 'widget#show', :as => :widget
  post  '/widget/:title/rate' => 'widget#rating_create', :as => :ratings
  put   '/widget/:title/rate' => 'widget#rating_update', :as => :ratings

  # Widget code (hijacking paperclip's route)
  get   '/widget/:title/:version/download' => "widget#download", :as => :widget_download
  get   '/widget/:title/:version/backend/download' => "widget#download_backend", :as => :widget_download_backend

  # Widget Submission (Versions)
  resources :versions, :path => "submit", :controller => "submit"

  # Users
  get '/user/:id-:url_title' => 'user#index', :as => :user

  # My Widgets
  match '/mywidgets' => 'mywidgets#index', :as => :mywidgets
  match '/mywidgets/submissions' => 'mywidgets#submissions', :as => :mywidgets_submissions

  # SDK
  match '/sdk' => 'sdk#index', :as => :sdk
  match '/sdk/*section' => 'sdk#sdk_section'
  match '/zippedwidget' => 'widget_generator#zippedwidget'


  # Admin section
  match '/admin/users' => 'admin#users', :as => :admin_users
  match '/admin/users/admin' => 'admin#adminusers', :as => :admin_admin_users
  match '/admin/users/delete/:id' => 'admin#delete_user', :as => :admin_delete_user
  match '/admin/options' => 'admin#options', :as => :admin_options
  match '/admin/languages/edit/:id' => 'admin#edit_language', :as => :admin_edit_language
  post  '/admin/languages/save' => 'admin#save_language', :as => :admin_add_edit_language
  delete  '/admin/languages/remove/:id' => 'admin#remove_language', :as => :admin_remove_language
  match '/admin/categories' => 'admin#categories', :as => :admin_categories
  match '/admin/categories/edit/:id' => 'admin#edit_category', :as => :admin_edit_category
  post  '/admin/categories/save' => 'admin#save_category', :as => :admin_add_edit_category
  delete '/admin/categories/remove/:id' => 'admin#remove_category', :as => :admin_remove_category
  match '/admin/statistics' => 'admin#statistics', :as => :admin_statistics
  match '/admin' => 'admin#widgets'
  match '/admin/widgets(/:state)' => 'admin#widgets', :as => :admin
  match '/admin/widgets/:review/:version_id' => 'admin#reviewed', :as => :admin_review_widget
  post  '/admin/users/update' => 'admin#user_update', :as => :update

  # Errors
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#e404'
  end
  get "errors/e404"
  get "errors/e500"

  root :to => 'home#index'

end

app/controllers/mywidgets_controller.rb
class MywidgetsController < ApplicationController
  before_filter :authenticated
  layout 'lhnavigation'

  def index
    order = get_sort

    @widgets = Widget.where(:user_id => current_user.id, :active => true).order(order).page(params[:page])
    @count = Widget.count(:conditions => {:user_id => current_user.id})

    if request.xhr?
      render :partial => "pagewidgets/widget_list"
    end
  end

  def submissions
    @widgets = Widget.where(:user_id => current_user.id).includes(:versions).order("versions.created_at desc, versions.reviewed_on desc")
  end

  def authenticated
    if !user_signed_in?
      redirect_to :root
    end
  end

end

app/views/mywidgets/_lhnav.html.erb
<nav id="lhnavigation_container">
  <h1 class="wl-bold">My Widgets</h1>
  <ul>
      <li<% if params[:action].eql?"index" %> class="selected wl-bold"<% end %>>
        <div><%= link_to "Approved Widgets", "/mywidgets"%></div>
      </li>
      <li<% if params[:action].eql?"submissions" %> class="selected wl-bold"<% end %>>
        <div><%= link_to "Submissions", "/mywidgets/submissions" %></div>
      </li>
  </ul>
  <%= render :partial => "pagewidgets/submitwidget" %>
</nav>
<hr class="wl-push wl-hidden"/>

app/views/mywidgets/_version.html.erb
<% if row %><tr><% end %>
  <td><%= version.created_at.localtime.strftime("%B %e, %Y %l:%M%P") %></td>
  <td><%= version.version_number %></td>
  <td><%= version.state.title %></td>
  <td><%= version.notes %></td>
  <td>
    <% if version.state_id.eql? State.pending %>
    <%= button_to "delete", version_path(version.id),
      :method => :delete,
      :confirm => "Are you sure you want to delete this submission? There is no undo.",
      :class => "wl-link-button" %>
    <% end %>
  </td>
<% if row %></tr><% end %>

app/views/mywidgets/_widget.html.erb
<% versions = widget.versions %>
<% title = widget.title || Version.where(:widget_id => widget.id).order("created_at desc").limit(1).first.title %>
<tr>
  <td rowspan="<%= versions.size %>"><%= link_to title, widget_path(:title => widget.url_title), :class => "wl-regular-link wl-bold wl-widget-item_widgetname" %></td>
  <%= render :partial => 'version', :locals => {:version => versions.first, :row => false} %>
  <td rowspan="<%= versions.size %>"><%= link_to "submit new version", edit_version_path(widget.id), :class => "wl-regular-link wl-bold wl-widget-item_widgetname" %></td>
</tr>
<%= render :partial => 'version', :collection => versions[1..-1], :locals => {:row => true} %>
<tr><td colspan="6" class="spacer"></td></tr>

app/views/mywidgets/index.html.erb
<% content_for :title do %> - Your Approved Widgets<% end %>

<div id="mywidgets">
    <%= render :partial => "pagewidgets/widget_list", :locals => {:noresults => {:message => "You don't have any approved widgets.", :icon => 'widget'}} %>
</div>
<hr class="wl-push wl-hidden"/>

app/views/mywidgets/submissions.html.erb
<% content_for :title do %> - Your Widget Submissions<% end %>

<% if @widgets.size > 0 %>
<div id="mywidgets">
  <table>
    <colgroup span="6">
      <col class="mywidgets_submissions_title"></col>
      <col class="mywidgets_submissions_date"></col>
      <col class="mywidgets_submissions_version"></col>
      <col class="mywidgets_submissions_state"></col>
      <col class="mywidgets_submissions_notes"></col>
      <col class="mywidgets_submissions_retract"></col>
      <col class="mywidgets_submissions_actions"></col>
    </colgroup>
    <thead>
      <tr>
        <th>Widget</th><th>Date</th><th>Version</th><th>State</th><th>Notes</th><th></th><th></th>
      </tr>
    </thead>
    <tbody>
      <tr><td colspan="5" class="spacer"></td></tr>
      <%= render :partial => "widget", :collection => @widgets %>
    </tbody>
  </table>
</div>
<hr class="wl-push wl-hidden"/>
<% else %>
  <%= render :partial => "pagewidgets/widget_list", :locals => {:noresults => {:message => "You don't have any submissions.", :icon => 'widget'}} %>
<% end %>