config/routes.rb
SakaiWidgetlibrary::Application.routes.draw do

  # Routes for devise authentication
  devise_for :users, :controllers => {:sessions => 'sessions'}, :skip => [:sessions] do
    get  '/' => "home#index", :as => :new_user_session
    post '/login' => 'sessions#create', :as => :user_session
    get  '/logout' => 'devise/sessions#destroy', :as => :logout
    get  '/register' => 'devise/registrations#new', :as => :user_registration
    post '/register' => 'registrations#create', :as => :user_registration
    get  '/register' => 'devise/registrations#new', :as => :new_user_registration
    get  '/register/check_username/:username' => 'registrations#check_username'
    get  '/forgot_password' => 'devise/passwords#new', :as => :new_user_password
    post '/forgot_password' => 'passwords#create', :as => :user_password
    put  '/forgot_password' => 'passwords#update', :as => :user_password
    put  '/register' => 'registrations#update', :as => :edit_user_registration
    get  '/edit' => 'devise/registrations#edit', :as => :edit_user_registration
  end

  # Application-level routes
  match '/search' => 'application#search'

  # Browse
  match '/browse(/:category_title)' => 'browse#index', :as => :browse

  # Widget Details
  get   '/widget/:title' => 'widget#show', :as => :widget
  post  '/widget/:title/rate' => 'widget#rating_create', :as => :ratings
  put   '/widget/:title/rate' => 'widget#rating_update', :as => :ratings

  # Widget code (hijacking paperclip's route)
  get   '/widget/:title/:version/download' => "widget#download", :as => :widget_download
  get   '/widget/:title/:version/backend/download' => "widget#download_backend", :as => :widget_download_backend

  # Widget Submission (Versions)
  resources :versions, :path => "submit", :controller => "submit"

  # Users
  get '/user/:id-:url_title' => 'user#index', :as => :user

  # My Widgets
  match '/mywidgets' => 'mywidgets#index', :as => :mywidgets
  match '/mywidgets/submissions' => 'mywidgets#submissions', :as => :mywidgets_submissions

  # SDK
  match '/sdk' => 'sdk#index', :as => :sdk
  match '/sdk/*section' => 'sdk#sdk_section'
  match '/zippedwidget' => 'widget_generator#zippedwidget'


  # Admin section
  match '/admin/users' => 'admin#users', :as => :admin_users
  match '/admin/users/admin' => 'admin#adminusers', :as => :admin_admin_users
  match '/admin/users/delete/:id' => 'admin#delete_user', :as => :admin_delete_user
  match '/admin/options' => 'admin#options', :as => :admin_options
  match '/admin/languages/edit/:id' => 'admin#edit_language', :as => :admin_edit_language
  post  '/admin/languages/save' => 'admin#save_language', :as => :admin_add_edit_language
  delete  '/admin/languages/remove/:id' => 'admin#remove_language', :as => :admin_remove_language
  match '/admin/categories' => 'admin#categories', :as => :admin_categories
  match '/admin/categories/edit/:id' => 'admin#edit_category', :as => :admin_edit_category
  post  '/admin/categories/save' => 'admin#save_category', :as => :admin_add_edit_category
  delete '/admin/categories/remove/:id' => 'admin#remove_category', :as => :admin_remove_category
  match '/admin/statistics' => 'admin#statistics', :as => :admin_statistics
  match '/admin' => 'admin#widgets'
  match '/admin/widgets(/:state)' => 'admin#widgets', :as => :admin
  match '/admin/widgets/:review/:version_id' => 'admin#reviewed', :as => :admin_review_widget
  post  '/admin/users/update' => 'admin#user_update', :as => :update

  # Errors
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#e404'
  end
  get "errors/e404"
  get "errors/e500"

  root :to => 'home#index'

end

app/models/widget.rb
class Widget < ActiveRecord::Base

  belongs_to :user
  belongs_to :version
  has_many :ratings
  has_many :versions, :order => "created_at desc"
  has_many :downloads

  accepts_nested_attributes_for :versions, :allow_destroy => true

  attr_accessible :url_title, :downloads

  validates_presence_of :url_title
  validates_uniqueness_of :url_title

  def approved_versions
    Version.where(:state_id => State.accepted, :widget_id => self.id)
  end

  def active_version
    self.version
  end

  def latest_version
    Version.where(:widget_id => self.id).order("created_at desc").limit(1).first
  end

  def method_missing(m, *args, &block)
    # pass through any methods that the active_version has
    if !self.active_version.nil? && self.active_version.respond_to?(m)
      self.active_version.method(m).call(*args, &block)
    elsif self.respond_to?(m)
      super(m, *args, &block)
    else
      nil
    end
  end

end

app/controllers/widget_controller.rb
class WidgetController < ApplicationController
  def show
    widget_title = params[:title]
    @widget = Widget.first( :conditions => { :url_title => widget_title } )

    if !@widget || (!can_view_admin_area? && (!@widget.active_version && @widget.user != current_user))
      not_found
    end

    if can_view_in_progress_widget
      if (@widget.latest_version != @widget.version) || (@widget.versions.size == 1 && !@widget.state.id.eql?(State.accepted))
        @latest_version = @widget.latest_version
        unless @latest_version.state.id.eql?(State.declined)
          @widget.version = Version.where(:widget_id => @widget.id).order("created_at desc").limit(1).first
        end
      end

      if !@widget.version
        @widget.version = Version.where(:widget_id => @widget.id).order("created_at desc").limit(1).first
      end
    end

    @versions = @widget.approved_versions.order("version_number desc")
    @related = Widget.where(:active => true).limit(5)
    if user_signed_in?
      @rating = Rating.where(:user_id => current_user.id, :widget_id => @widget.id).first || Rating.new
    end
  end

  def update_average_rating(widget_id)
    ratings = Rating.where(:widget_id => widget_id)
    widget = Widget.where(:id => widget_id).first

    total_stars = 0

    ratings.each do |rating|
      total_stars += rating.stars
    end

    widget.average_rating = total_stars.to_f / ratings.size.to_f
    widget.num_ratings = ratings.size
    widget.save
  end

  def rating_create
    if Widget.find(params[:rating][:widget_id]).user.id != current_user.id
      @rating = Rating.new(params[:rating])
      if @rating.save
        update_average_rating(params[:rating][:widget_id])
      end
    end

    respond_to do |format|
      format.js
    end
  end

  def rating_update
    @rating = Rating.where(:user_id => current_user.id, :widget_id => params[:rating][:widget_id]).first
    if @rating
      @rating.update_attributes(params[:rating])
      if @rating.save
        update_average_rating(params[:rating][:widget_id])
      end
    end

    respond_to do |format|
      format.js
    end
  end

  def log_download(widget, version, kind)
    if !widget.active
      return
    end
    exists = Download.where(["widget_id = ? AND (user_id = ? OR ip_address = ?)", widget.id, current_user ? current_user.id : nil, request.remote_ip])
    # Always log the download, even if it exists
    download = Download.new
    download.widget_id = widget.id
    download.version_id = version.id
    if current_user
      download.user_id = current_user.id
      download.unique_id = current_user.id
    else
      download.ip_address = request.remote_ip
      download.unique_id = request.remote_ip
    end

    # only increment the downloads on the widget if this is a unique download
    unless exists.size > 0
      widget.num_downloads += 1
      widget.save
    end

    download.save
  end

  def download
    version = Version.find(params[:version])
    widget = Widget.first( :conditions => { :url_title => params[:title] } )
    log_download(widget, version, "code")
    send_file version.code.path, :type => version.code_content_type
  end

  def download_backend
    version = Version.find(params[:version])
    widget = Widget.first( :conditions => { :url_title => params[:title] } )
    log_download(widget, version, "bundle")
    send_file version.bundle.path, :type => version.bundle_content_type
  end

  protected
  def can_view_in_progress_widget
    @widget.user == current_user || can_view_admin_area?
  end

end

app/helpers/widget_helper.rb
# encoding: utf-8

module WidgetHelper

  def review_description(review)
    output = h truncate(review.review, :length => 250, :separator => ' ', :omission => ' ')
    output += button_tag("read more", :type => 'button', :class => 'review_read_more wl-link-button') if review.review.size > 250
    output.html_safe
  end

end

app/views/widget/_admin_actions.html.erb
<div id="admin_actions" data-versionid="<%= @latest_version.id %>" class="wl-widget-item-container">
  <h1>Review actions</h1>
  <div id="admin_action_buttons">
    <button data-action="approve" class="wl-button wl-overlay-button">Approve this widget</button>
    <button data-action="reject" class="wl-button">Reject this widget</button>
  </div>
  <div id="reject_confirm" class="widget_confirmation" style="display:none">
    <h2>Rejecting widget</h2>
    <label for="reject_message">Reason for declining and/or steps to improve and fix the widget:</label>
    <textarea id="reject_message" placeholder="Please update the design to conform to our design standards as per the SDK."></textarea>
    <button data-action="confirm" data-which="reject" class="wl-button">Confirm rejection</button>
    <button class="wl-button wl-link-button" data-action="cancel">Cancel</button>
  </div>
  <div id="approve_confirm" class="widget_confirmation" style="display:none">
    <h2>Approving widget</h2>
    <label for="approve_message">Note to user:</label>
    <textarea id="approve_message" placeholder="This widget is awesome! Way to go!"></textarea>
    <button data-action="confirm" data-which="approve" class="wl-button wl-overlay-button">Confirm approval</button>
    <button class="wl-button wl-link-button" data-action="cancel">Cancel</button>
  </div>
</div>
<%= javascript_include_tag :admin %>
<%= stylesheet_link_tag :admin %>

app/views/widget/_description.html.erb
<div id="widget_description_container">
  <% if can_view_admin_area? && @widget.state.title.eql?("pending") %>
    <%= render :partial => "admin_actions" %>
  <% end %>
  <hr class="wl-split-line" style="display:none;"/>
  <div id="widget_download">
      <%= image_tag @widget.icon.url(:medium), :alt => "#{@widget.title} preview" %>
      <%= link_to "Download", "/system/codes/#{@widget.id}/original/#{@widget.code_file_name}", :target => "_blank", :class => "wl-button wl-header-button"%>
  </div>
  <div id="widget_description">
      <h1 class="wl-bold"><%= @widget.title %> <span id="widget_version"></span></h1>
      by <%= link_to @widget.user.name, developer_page_path({:developer_name => @widget.user.url_title}), :class => "wl-regular-link" %>
      <p><%= @widget.description %></p>
  </div>
  <div id="widget_details">
      <div>
          <%= render :partial => "pagewidgets/rating", :locals => { :stars => @widget.average_rating, :num_ratings => @widget.ratings.size, :display => { :num_ratings => true } } %>
          <hr class="wl-push wl-hidden"/>
      </div>
      <hr class="wl-split-line wl-push"/>
      <h1>Information</h1>
      <ul>
          <% if @widget.categories.size > 0 %>
          <li><span>Categories:</span>
            <ul>
              <% @widget.categories.each do |category| %>
                <li><%= link_to category.title, category_path({:category_title => category.url_title}), :class => "wl-regular-link" %></li>
              <% end %>
            </ul>
          </li>
          <% end %>
          <li><span>Developer:</span><span><%= link_to @widget.user.name, developer_page_path({:developer_name => @widget.user.url_title}), :class => "wl-regular-link" %></span></li>
          <% if @widget.languages.size > 0 %>
          <li>
            <span>Languages:</span>
              <ul>
                <% @widget.languages.each do |language| %>
                  <li><%= language.title %></li>
                <% end %>
              </ul>
          </li>
          <% end %>
          <% if @widget.released_on %>
            <li><span>Released:</span><span><%= @widget.released_on.strftime("%B %e, %Y") %></span></li>
          <% end %>
      </ul>
  </div>
</div>
<hr class="wl-push wl-hidden"/>

app/views/widget/_details.html.erb
<% has_screenshots = @widget.screenshots.size > 0 %>
<div id="widgetdetails_container">
    <div class="wl-inpage-tabs">
      <% if has_screenshots %>
      <div class="wl-inpage-tab selected" id="screenshot_tab">Screenshots</div>
      <div class="wl-inpage-tab" id="reviews_tab">Reviews</div>
      <div class="wl-inpage-tab" id="versions_tab">Uploaded versions</div>
      <% else %>
      <div class="wl-inpage-tab selected" id="reviews_tab">Reviews</div>
      <div class="wl-inpage-tab" id="versions_tab">Uploaded versions</div>
      <% end %>
    </div>
    <div class="wl-inpage-tab-content">
        <div id="widgetdetails_screenshots" class="widgetdetails_tabcontent_content"<% if !has_screenshots %>style="display:none"<% end %>>
            <div id="widgetdetails_newestreviews">
                <% if @widget.ratings.size > 0 %>
                <h1>Latest reviews</h1>
                <%= render :partial => "core/review", :locals => { :display => { :rate_widget => true } }, :collection => @widget.ratings.limit(3) %>
                <hr class="wl-push wl-hidden"/>
                <% end %>
                <% if user_signed_in? && current_user.id != @widget.user.id %>
                  <button class="wl-button wl-header-button" id="write_review">Write a review</a>
                <% end %>
            </div>

            <div id="widgetdetails_screenshot_container">
              <%= render :partial => "screenshots" %>
            </div>
        </div>

        <div id="widgetdetails_reviews" class="widgetdetails_tabcontent_content" <% if has_screenshots %>style="display:none;"<% end %>>
            <% if user_signed_in? && current_user.id != @widget.user.id #Only allow logged in users to review %>
                <%= form_for(@rating, :url => "/widget/#{@widget.url_title}/rate") do |f| %>
                <div id="widgetdetails_reviews_review_widget">
                    <h1>Review this widget</h1>
                    <%= f.text_area :review, :placeholder => "Write a review" %>
                    <%= f.hidden_field :widget_id, :value => @widget.id %>
                    <%= f.hidden_field :user_id, :value => @rating.user_id || current_user.id %>
                    <%= f.hidden_field :stars , :value => @rating.stars.to_i, :class => 'wl-rating-input' %>
                    <%= render :partial => "pagewidgets/rating", :locals => { :display => { :rate_widget => true }, :stars => @rating.stars, :num_ratings => @widget.ratings.size } %>
                    <%= f.submit "Post review", :class => "wl-button wl-header-button" %>
                </div>
                <% end %>
            <% end %>
            <div id="widgetdetails_reviews_all">
                <%= render :partial => "core/review", :locals => { :display => { :rate_widget => true } }, :collection => @widget.ratings %>
            </div>
        </div>

        <div id="widgetdetails_versions" class="widgetdetails_tabcontent_content" style="display:none;">
            <h1>Versions</h1>
            <hr class="wl-split-line" id="widgetdetails_uploadedversions_headerline"/>
            <% @versions.each do |version| %>
                <% if version.languages.size > 0 %>
                  <div class="widgetdetails_uploadedversions_versionlanguage">
                      <p>Languages:</p>
                      <p><%= version.languages.collect{|l| l = l.title}.join(", ") %></p>
                  </div>
                <% end %>
                <div class="widgetdetails_uploadedversions_versiondescription">
                    <%= link_to version.title + " " + version.version_number, "javascript:;", :class => "wl-regular-link wl-bold" %>
                    <span class="widgetdetails_uploadeversions_dateuuploaded"> - released <%= version.released_on.strftime("%B %d, %Y") %></span>
                    <p class="widgetdetails_uploadedversions_mainfeatures">Main features:</p>
                    <p><%= version.features %></p>
                </div>

                <hr class="wl-split-line"/>
            <% end %>

        </div>
    </div>
    <hr class="wl-push wl-hidden">
</div>

app/views/widget/_rating_result.js.erb
// If it is a success, just redirect to the URL returned
<% unless @rating.errors.any? %>
  window.location.reload();
<% else %>
  var errors = <%=raw translate_errors(@rating).to_json %>;

  WL.reset_errors();

  $.each(errors, function(key, error) {
      if (key === "stars"){
          $("#rating_" + key).siblings(".wl-rating-container").addClass(WL.wlError);
      } else {
          $("#rating_" + key).addClass(WL.wlError);
      }
      $("#rating_" +  key + "_error").text(error.message).show();
  });
<% end %>

app/views/widget/_relatedwidgets.html.erb
<div id="widgetlibrary_relatedwidgets" class="wl-inset-shadow-container">
    <h1>Related widgets</h1>
    <%= render :partial => "core/widget", :locals => {:display => {:rating => true, :author => true, :num_ratings => true}}, :collection => @related %>
    <hr class="wl-push wl-hidden"/>
</div>

app/views/widget/_screenshots.html.erb
<% if @widget.screenshots.size > 0 %>
  <div id="widgetdetails_screenshot_active">
    <%= image_tag @widget.screenshots[0].image.url(:medium), :alt => "#{@widget.title} Screenshot", :id => "widgetdetails_main_screenshot" %>
  </div>
  <div id="widgetdetails_screenshots_thumbs">
    <% @widget.screenshots.each_index do |i| %>
      <% cssclass = if i.eql? 0 then "selected" else "" end %>
      <div class="widgetdetails_screenshots_thumb <%= cssclass %>">
          <div class="widgetdetails_screenshots_thumb_container">
            <%= image_tag @widget.screenshots[i].image.url(:thumb), :alt => "#{@widget.title} Screenshot", "data-large-src" => @widget.screenshots[i].image.url(:medium) %>
          </div>
          <div class="underline"></div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/widget/_tabs.html.erb
<%
has_screenshots = @widget.screenshots.size > 0
selected = "screenshots"
if !has_screenshots || params[:show].eql?("reviews")
  selected = "reviews"
elsif params[:show].eql?("versions")
  selected = "versions"
end
%>
<div id="widgetdetails_container">
    <div class="wl-inpage-tabs">
      <% if has_screenshots %>
        <div class="wl-inpage-tab<% if selected.eql?("screenshots") %> selected<% end %>" id="screenshots">Screenshots</div>
      <% end %>
      <div class="wl-inpage-tab<% if selected.eql?("reviews") %> selected<% end %>" id="reviews">Reviews</div>
      <div class="wl-inpage-tab<% if selected.eql?("versions") %> selected<% end %>" id="versions">Uploaded versions</div>
    </div>
    <div class="wl-inpage-tab-content">
      <% if has_screenshots %>
        <div id="widgetdetails_screenshots" class="widgetdetails_tabcontent_content<%= if selected.eql?("screenshots") then " selected" end %>"<% unless selected.eql?("screenshots") %> style="display:none"<% end %>>
            <div id="widgetdetails_newestreviews">
                <% if @widget.ratings.size > 0 %>
                <h1>Latest reviews</h1>
                <%= render :partial => "core/review_list", :locals => { :ratings => @widget.ratings.limit(3) } %>
                <hr class="wl-push wl-hidden"/>
                <% end %>
                <% if user_signed_in? && current_user.id != @widget.user.id %>
                  <%= link_to "Write a review", widget_path(:title => @widget.url_title) + "?show=reviews", :id => "write_review", :class => "wl-button wl-header-button wl-link-button" %>
                <% end %>
            </div>

            <div id="widgetdetails_screenshot_container">
              <%= render :partial => "screenshots" %>
            </div>
        </div>
      <% end %>
        <div id="widgetdetails_reviews" class="widgetdetails_tabcontent_content<%= if selected.eql?("reviews") then " selected" end %>"<% unless selected.eql?("reviews") %> style="display:none;"<% end %>>
            <div id="widgetdetails_reviews_review_widget">
                <h1>Review this widget</h1>
                    <% if user_signed_in? && current_user.id != @widget.user.id %>
                        <%= form_for(@rating, :url => "/widget/#{@widget.url_title}/rate", :html => { :class => "wl-form-field-wrapper" }, :remote => true) do |f| %>
                            <span id="rating_review_error" class="wl-error" style="display:none"></span>
                            <%= f.text_area :review, :placeholder => "Write a review" %>
                            <%= f.hidden_field :widget_id, :value => @widget.id %>
                            <%= f.hidden_field :user_id, :value => @rating.user_id || current_user.id %>
                            <%= f.hidden_field :stars , :value => @rating.stars.to_i, :class => 'wl-rating-input' %>
                            <span id="rating_stars_error" class="wl-error" style="display:none"></span>
                            <%= render :partial => "pagewidgets/rating", :locals => { :display => { :rate_widget => true }, :stars => @rating.stars, :num_ratings => @widget.ratings.size } %>
                            <%= f.submit "Post review", :class => "wl-button wl-header-button" %>
                        <% end %>
                    <% elsif !user_signed_in? %>
                        <p>Please sign in or <%= link_to "create an account", user_registration_path, :class => "wl-regular-link" %> to post a review.</p>
                    <% else %>
                        <p>You can't review your own widget.</p>
                    <% end %>
            </div>
            <div id="widgetdetails_reviews_all">
                <%= render :partial => "core/review_list", :locals => { :ratings => @widget.ratings } %>
            </div>
        </div>

        <div id="widgetdetails_versions" class="widgetdetails_tabcontent_content<%= if selected.eql?("versions") then " selected" end %>"<% unless selected.eql?("versions") %> style="display:none;"<% end %>>
            <h1>Versions</h1>
            <hr class="wl-split-line" id="widgetdetails_uploadedversions_headerline"/>
            <% @versions.each do |version| %>
                <% if version.languages.size > 0 %>
                  <div class="widgetdetails_uploadedversions_versionlanguage">
                      <p>Languages:</p>
                      <p><%= version.languages.collect{|l| l = l.title}.join(", ") %></p>
                  </div>
                <% end %>
                <div class="widgetdetails_uploadedversions_versiondescription">
                    <%= link_to version.title + " " + version.version_number, widget_download_path(:title => @widget.url_title, :version => version.id), :class => "wl-regular-link wl-bold" %>
                    <span class="widgetdetails_uploadeversions_dateuuploaded"> - released <%= version.released_on.strftime("%B %d, %Y") %></span>
                    <p class="widgetdetails_uploadedversions_mainfeatures">Main features:</p>
                    <p><%= version.features %></p>
                </div>

                <hr class="wl-split-line"/>
            <% end %>

        </div>
    </div>
    <hr class="wl-push wl-hidden">
</div>

app/views/widget/_top_info.html.erb
<div id="widget_description_container">
  <% if @latest_version %>
    <% if can_view_admin_area? && @latest_version.state.id.eql?(State.pending) %>
      <%= render :partial => "admin_actions" %>
    <% end %>
    <div id="latest_version">
      <%
        if @latest_version.state.id.eql?(State.pending)
          state = "is pending review"
          hclass = "widget_declined_header"
        else
          state = "has been declined"
          hclass = "widget_declined_header"
        end
      %>
      <h1 class="<%= hclass %>">Version <%= @latest_version.version_number %>, submitted on <%= @latest_version.created_at.localtime.strftime("%B %e, %Y %l:%M%P") %>, <%= state %></h1>
      <% if @latest_version.state.id.eql?(State.declined) && @latest_version.notes %>
        <h3>Notes from the reviewer:</h3>
        <pre><%= word_wrap @latest_version.notes, 110 %></pre>
      <% end %>
    </div>
  <% end %>
  <% if @widget.user == current_user %>
    <div id="new_version_container">
      <%= link_to "Submit a new version", edit_version_path(@widget.id), :class => "wl-regular-link wl-bold submit_new_version_link" %>
    </div>
  <% end %>
  <hr class="wl-split-line" style="display:none;"/>
  <div id="widget_download">
      <%= image_tag @widget.icon.url(:medium), :alt => "#{@widget.title} preview" %>
      <%= link_to "Download", widget_download_path(:title => @widget.url_title, :version => @widget.version.id), :class => "wl-button wl-header-button", :id => "widget_download_button" %>
      <% if @widget.bundle.file? %>
        <%= link_to "Download Back-end Bundle", widget_download_backend_path(:title => @widget.url_title, :version => @widget.version.id), :class => "wl-button wl-header-button"%>
      <% end %>
  </div>
  <div id="widget_description">
      <h1 class="wl-bold"><%= @widget.title %> <span id="widget_version"></span></h1>
      by <%= link_to @widget.user.name, user_path(:id => @widget.user.id, :url_title => @widget.user.url_title), :class => "wl-regular-link" %>
      <p><%= @widget.description %></p>
      <p><%= @widget.features %></p>
  </div>
  <div id="widget_details">
      <div>
          <%= render :partial => "pagewidgets/rating", :locals => { :stars => @widget.average_rating, :num_ratings => @widget.ratings.size, :display => { :num_ratings => true }, :widget => @widget } %>
          <hr class="wl-push wl-hidden"/>
      </div>
      <hr class="wl-split-line wl-push"/>
      <h1>Information</h1>
      <ul>
          <% if @widget.categories.size > 0 %>
          <li><span>Categories:</span>
            <ul>
              <% @widget.categories.each do |category| %>
                <li><%= link_to category.title, browse_path({:category_title => category.url_title}), :class => "wl-regular-link" %></li>
              <% end %>
            </ul>
          </li>
          <% end %>
          <li><span>Developer:</span><span><%= link_to @widget.user.name, user_path(:id => @widget.user.id, :url_title => @widget.user.url_title), :class => "wl-regular-link" %></span></li>
          <% if @widget.languages.size > 0 %>
          <li>
            <span>Languages:</span>
              <ul>
                <% @widget.languages.each do |language| %>
                  <li><%= language.title %></li>
                <% end %>
              </ul>
          </li>
          <% end %>
          <% if @widget.version_number %>
            <li><span>Version:</span><span><%= @widget.version_number %></span></li>
          <% end %>
          <% if @widget.released_on %>
            <li><span>Released:</span><span><%= @widget.released_on.strftime("%B %e, %Y") %></span></li>
          <% end %>
          <% unless @widget.widget_repo.blank? %>
            <li><span>Source repository:</span><span><%= link_to @widget.widget_repo, @widget.widget_repo, :class => "wl-regular-link" %></span></li>
          <% end %>
          <% unless @widget.widget_backend_repo.blank? %>
            <li><span>Backend source repository:</span><span><%= link_to @widget.widget_backend_repo, @widget.widget_backend_repo, :class => "wl-regular-link" %></span></li>
          <% end %>
      </ul>
  </div>
</div>
<hr class="wl-push wl-hidden"/>

app/views/widget/index.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "widget" %>
<% end %>

<div class="wl-content-container" id="widget_container">
    <%= render :partial => "pagewidgets/widgetdescription" %>
    
    <%= render :partial => "pagewidgets/widgetdetails" %>
    
    <%= render :partial => "pagewidgets/relatedwidgets" %>
    <hr class="wl-hidden wl-push"/>
</div>

app/views/widget/rating_create.js.erb
<%= render :partial => "rating_result" %>

app/views/widget/rating_update.js.erb
<%= render :partial => "rating_result" %>

app/views/widget/show.html.erb
<% content_for :title do %> - <%= @widget.title %><% end %>

<div class="wl-content-container" id="widget_container">
    <%= render :partial => "top_info" %>
    
    <%= render :partial => "tabs" %>

    <%= render :partial => "relatedwidgets" %>

    <hr class="wl-hidden wl-push"/>
</div>